### ISSUE TITLE
Examples in README

### ISSUE THREAD

**Issue by parry84** [jesuswasrasta/KataFarkle#1]
Is it correct that the two 1s in the second example of README add +50 points each one, rather than +100?

**Comment by jesuswasrasta** [comment]
No, it's a mistake! Thank to pointing me out :smiley:

**Comment by jesuswasrasta** [comment]
Fixed :smirk:

**Comment by parry84** [comment]
Thanks, I also noticed another issue into first example: total score should be 200 rather than 250

**Comment by jesuswasrasta** [comment]
Oh my... :joy: 
I pushed the repo before using it for the first time in a workshop while in a hurry, these are the results... :blush:    
In the meantime I realized I fixed examples on my local computer, but never committed nor pushed.  
Thanks!

Are you playing with this kata?  
Are you enjoining it? :relaxed:

**Comment by parry84** [comment]
I noticed the fixes, thank you for your prompt resolution.
I attended the meetup last year, now I was trying to redo the kata by myself :)
